POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Творожные пончики в сахарной пудре",
  "timeForPreparing": 40,
  "ingredient": [
    {
      "name": "Творог",
      "count": 250,
      "measure": "г."
    },
    {
      "name": "Куриное яйцо",
      "count": 3,
      "measure": "шт."
    },
    {
      "name": "Пшеничная мука",
      "count": 8,
      "measure": "ст.л."
    },
    {
      "name": "Сахар",
      "count": 2,
      "measure": "Столовые ложки"
    },
    {
      "name": "Соль",
      "count": 10,
      "measure": "г."
    },
    {
      "name": "Оливковое масло",
      "count": 10,
      "measure": "г."
    },
    {
      "name": "Сода",
      "count": 2,
      "measure": "г."
    },
    {
      "name": "Сахарная пудра с ванилью",
      "count": 5,
      "measure": "г."
    }
  ],
  "steps": [
    "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции.",
    "В небольшом сотейнике оливковое масло хорошо разогреть.",
    "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха.",
    "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином."
  ]
}


###

GET http://localhost:8080/recipe/0

###

POST http://localhost:8080/ingredient
Content-Type: application/json

{
  "name": "Молоко",
  "count": 2,
  "measure": "Столовые ложки"
}
